openapi: 3.0.1
info:
  title: Power Plant Microservice
  description: The API documentation for Power Plant Microservice APIs
  contact:
    email: pasinduath@gmail.com
  license:
    name: Apache 2.0
  version: 1.0.0
servers:
  - url: https://localhost:8080/v1
    description: DEV environnement
tags:
  - name: Battery
    description: Battery related APIs
paths:
  /batteries:
    get:
      tags:
        - Battery
      summary: Get all batteries
      parameters:
        - in: query
          name: post_code_range
          schema:
            type: string
          description: start and end points of range (pattern 0000-9999)
          required: false
        - in: query
          name: page
          required: false
          schema:
            type: integer
          description: Page number that is need to be fetched
        - in: query
          name: page_size
          required: false
          schema:
            type: integer
          description: Number of entities that is need to be fetched in one page
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                required:
                  - totalCount
                  - averageCapacity
                  - items
                type: object
                properties:
                  totalCount:
                    type: integer
                    example: 3
                  averageCapacity:
                    type: number
                    example: 22.00
                  items:
                    type: array
                    items:
                      required:
                        - id
                        - name
                        - postcode
                        - capacity
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 3
                        name:
                          type: string
                          example: 'testName'
                        postcode:
                          type: string
                          example: '1233'
                        capacity:
                          type: integer
                          example: 3

        400:
          description: bad request
          content:
            application/json:
              schema:
                required:
                  - timestamp
                  - status
                  - message
                  - errors
                type: object
                properties:
                  timestamp:
                    type: string
                    example: '2022-06-05T14:54:46.140+00:00'
                  status:
                    type: string
                    example: 'BAD_REQUEST'
                  message:
                    type: string
                    example: "Invalid request"
                  errors:
                    type: array
                    items:
                      type: string
                      example: "invalid post_code_range"
        500:
          description: internal Server eroor
          content:
            application/json:
              schema:
                required:
                  - timestamp
                  - status
                  - error
                  - path
                type: object
                properties:
                  timestamp:
                    type: string
                    example: '2022-06-05T14:54:46.140+00:00'
                  status:
                    type: integer
                    example: 500
                  message:
                    type: string
                    example: "Internal Server Error"
                  errors:
                    type: string
                    example: "/v1/batteries"

    post:
      tags:
        - Battery
      summary: Post Battery
      requestBody:
        content:
          application/json:
            schema:
              required:
                - name
                - postcode
                - capacity
              type: object
              properties:
                name:
                  type: string
                  example: 'testName'
                postcode:
                  type: string
                  example: '1233'
                capacity:
                  type: integer
                  example: 3
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                required:
                  - id
                  - name
                  - postcode
                  - capacity
                type: object
                properties:
                  id:
                    type: integer
                    example: 3
                  name:
                    type: string
                    example: 'testName'
                  postcode:
                    type: string
                    example: '1233'
                  capacity:
                    type: integer
                    example: 3
        400:
          description: bad request
          content:
            application/json:
              schema:
                required:
                  - timestamp
                  - status
                  - message
                  - errors
                type: object
                properties:
                  timestamp:
                    type: string
                    example: '2022-06-05T14:54:46.140+00:00'
                  status:
                    type: string
                    example: 'BAD_REQUEST'
                  message:
                    type: string
                    example: "Invalid request"
                  errors:
                    type: array
                    items:
                      type: string
                      example: "postcode must not be null and postcode must be four digits"
        500:
          description: internal Server eroor
          content:
            application/json:
              schema:
                required:
                  - timestamp
                  - status
                  - error
                  - path
                type: object
                properties:
                  timestamp:
                    type: string
                    example: '2022-06-05T14:54:46.140+00:00'
                  status:
                    type: integer
                    example: 500
                  message:
                    type: string
                    example: "Internal Server Error"
                  errors:
                    type: string
                    example: "/v1/batteries"


  /bulk/batteries:
    post:
      tags:
        - Battery
      summary: Post Batteries
      requestBody:
        content:
          application/json:
            schema:
              items:
                required:
                  - name
                  - postcode
                  - capacity
                type: object
                properties:
                  name:
                    type: string
                    example: 'testName'
                  postcode:
                    type: string
                    example: '1233'
                  capacity:
                    type: integer
                    example: 3
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                items:
                  required:
                    - id
                    - name
                    - postcode
                    - capacity
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 3
                    name:
                      type: string
                      example: 'testName'
                    postcode:
                      type: string
                      example: '1233'
                    capacity:
                      type: integer
                      example: 3
        400:
          description: bad request
          content:
            application/json:
              schema:
                required:
                  - timestamp
                  - status
                  - message
                  - errors
                type: object
                properties:
                  timestamp:
                    type: string
                    example: '2022-06-05T14:54:46.140+00:00'
                  status:
                    type: string
                    example: 'BAD_REQUEST'
                  message:
                    type: string
                    example: "Invalid request"
                  errors:
                    type: array
                    items:
                      type: string
                      example: "Entity 2 : postcode must not be null and postcode must be four digits"
        500:
          description: internal Server eroor
          content:
            application/json:
              schema:
                required:
                  - timestamp
                  - status
                  - error
                  - path
                type: object
                properties:
                  timestamp:
                    type: string
                    example: '2022-06-05T14:54:46.140+00:00'
                  status:
                    type: integer
                    example: 500
                  message:
                    type: string
                    example: "Internal Server Error"
                  errors:
                    type: string
                    example: "/v1/bulk/batteries"



